# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
      - name: app
        image: log-generator:latest
        imagePullPolicy: Never
        env:
        - name: LOGSTASH_HOST
          value: "logstash.logging.svc.cluster.local"
        - name: LOGSTASH_PORT
          value: "5044"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          exec:
            command: ["python", "-c", "import sys; sys.exit(0)"]
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: log-generator-svc
spec:
  selector:
    app: log-generator
  ports:
    - protocol: TCP
      port: 8080